#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-workers-nextjs-saas-template"
main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudflare-workers-nextjs-saas"
database_id = "94dd1269-a29c-4621-adff-1762d1af6926"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "c6f2b077e0a34a84b3598558eb833055"

[vars]
EMAIL_FROM = "hello@saas-stack.startup-studio.dev"
EMAIL_FROM_NAME = "Startup Studio"
EMAIL_REPLY_TO = "startupstudio.dev@gmail.com"

# If using Resend don't forget to set the RESEND_API_KEY as a worker secret
# If using Brevo don't forget to set the BREVO_API_KEY as a worker secret
